name: chat #changing it will force you to change appname in import statement inside every .dart file.
description: Chattiing  & Calling Application

version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter_cache_manager: 3.3.0
  rxdart: ^0.27.7
  image_downloader: 0.31.0
  open_file: 3.2.1
  file_saver: 0.1.1
  gallery_saver: 2.3.2
  url_launcher: ^6.1.7
  circular_countdown_timer: ^0.2.3
  camera: ^0.10.0+4
  oktoast: ^3.3.1
  # helpers: 1.1.4
  holding_gesture: 1.1.0
  flutter_emoji: 2.4.0
  pip_view: ^0.9.7
  page_transition: ^2.0.9
  wechat_assets_picker: ^8.1.4
  image_editor: ^1.3.0
  video_editor: ^2.0.0
  flutter_image_compress: ^1.1.3
  mime: ^1.0.3
  video_compress:
    git:
      url: https://github.com/jonataslaw/videoCompress.git
      ref: a14d392
  link_preview_generator: 1.2.0
  google_mobile_ads: ^2.3.0
  font_awesome_flutter: ^10.2.1
  sms_autofill: 2.2.0
  receive_sharing_intent: 1.4.5
  firebase_crashlytics: ^3.0.6
  async: 2.10.0
  emoji_picker_flutter: ^1.5.1
  flutter_video_info: ^1.3.1
  group_button: ^5.2.2
  flutter_colorpicker: ^1.0.3
  # story_view: 0.13.2
  devicelocale: ^0.5.5
  http_auth: 1.0.1
  cloud_firestore: ^4.1.0
  flutter_cached_pdfview: 0.4.1
  fluttertoast: ^8.1.1
  firebase_messaging: ^14.1.2
  dio: 4.0.6
  cached_network_image: ^3.2.3
  firebase_storage: ^11.0.6
  device_info: 2.0.3
  file_picker: ^4.6.1
  path_provider: ^2.0.11
  flutter_sound: 9.2.13
  percent_indicator: 4.2.2
  string_validator: 0.3.0
  ntp: 2.0.0
  random_string: 2.3.1
  flutter_native_timezone: 2.0.0
  intl: 0.17.0
  connectivity: 3.0.6
  http: ^0.13.5
  provider: ^6.0.4
  firebase_auth: ^4.1.4
  html: ^0.15.1
  image_picker: ^0.8.6
  universal_platform: 1.0.0+1
  flutter_linkify: 5.0.2
  dotted_border: ^2.0.0+3
  diacritic: 0.1.3
  image_cropper: ^3.0.1
  contacts_service: 0.6.3
  share: 2.0.4
  scoped_model: ^2.0.0
  local_auth: 2.1.2
  crypto: ^3.0.2
  encrypt: 5.0.1
  localstorage: 4.0.0+1
  photo_view: ^0.14.0
  launch_review: 3.0.1
  overlay_support: ^2.1.0
  jiffy: ^5.0.0
  geolocator: ^9.0.2
  video_player: ^2.4.8
  video_thumbnail: ^0.5.3
  chewie: ^1.3.6
  media_info: ^0.12.0+1
  firebase_core: ^2.3.0
  shared_preferences: 2.0.15
  permission_handler: ^10.2.0
  agora_rtc_engine: ^6.0.0
  translator: 0.1.7
  audioplayers: ^1.1.1
  flutter_local_notifications: ^12.0.4
  flutter_secure_storage: ^6.1.0
  package_info: 2.0.2
  giphy_get: ^3.1.1
  wakelock: 0.6.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.15
  test: ^1.16.8

  flutter_launcher_icons: ^0.11.0
flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/appicon/appicon.jpg"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/sounds/
    - assets/flags/
    - lib/Services/localization/json_languages/
